/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OwnerCreateOrganizationRouteImport } from './routes/owner/create-organization'
import { Route as OwnerCreateAdminRouteImport } from './routes/owner/create-admin'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSetNewPasswordRouteImport } from './routes/auth/set-new-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardPostContentIndexRouteImport } from './routes/dashboard/post-content/index'
import { Route as LibraryIdPostIdRouteImport } from './routes/library/id.$postId'
import { Route as DashboardPostEditPostIdRouteImport } from './routes/dashboard/post-edit/$postId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCreateOrganizationRoute = OwnerCreateOrganizationRouteImport.update({
  id: '/owner/create-organization',
  path: '/owner/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCreateAdminRoute = OwnerCreateAdminRouteImport.update({
  id: '/owner/create-admin',
  path: '/owner/create-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetNewPasswordRoute = AuthSetNewPasswordRouteImport.update({
  id: '/auth/set-new-password',
  path: '/auth/set-new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostContentIndexRoute =
  DashboardPostContentIndexRouteImport.update({
    id: '/dashboard/post-content/',
    path: '/dashboard/post-content/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryIdPostIdRoute = LibraryIdPostIdRouteImport.update({
  id: '/library/id/$postId',
  path: '/library/id/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostEditPostIdRoute = DashboardPostEditPostIdRouteImport.update({
  id: '/dashboard/post-edit/$postId',
  path: '/dashboard/post-edit/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/set-new-password': typeof AuthSetNewPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/owner/create-admin': typeof OwnerCreateAdminRoute
  '/owner/create-organization': typeof OwnerCreateOrganizationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/post-edit/$postId': typeof DashboardPostEditPostIdRoute
  '/library/id/$postId': typeof LibraryIdPostIdRoute
  '/dashboard/post-content/': typeof DashboardPostContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/set-new-password': typeof AuthSetNewPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/owner/create-admin': typeof OwnerCreateAdminRoute
  '/owner/create-organization': typeof OwnerCreateOrganizationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/post-edit/$postId': typeof DashboardPostEditPostIdRoute
  '/library/id/$postId': typeof LibraryIdPostIdRoute
  '/dashboard/post-content': typeof DashboardPostContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/set-new-password': typeof AuthSetNewPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/owner/create-admin': typeof OwnerCreateAdminRoute
  '/owner/create-organization': typeof OwnerCreateOrganizationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/post-edit/$postId': typeof DashboardPostEditPostIdRoute
  '/library/id/$postId': typeof LibraryIdPostIdRoute
  '/dashboard/post-content/': typeof DashboardPostContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/set-new-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/owner/create-admin'
    | '/owner/create-organization'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/post-edit/$postId'
    | '/library/id/$postId'
    | '/dashboard/post-content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/set-new-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/owner/create-admin'
    | '/owner/create-organization'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/post-edit/$postId'
    | '/library/id/$postId'
    | '/dashboard/post-content'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/set-new-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/update-password'
    | '/owner/create-admin'
    | '/owner/create-organization'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/post-edit/$postId'
    | '/library/id/$postId'
    | '/dashboard/post-content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSetNewPasswordRoute: typeof AuthSetNewPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  OwnerCreateAdminRoute: typeof OwnerCreateAdminRoute
  OwnerCreateOrganizationRoute: typeof OwnerCreateOrganizationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardPostEditPostIdRoute: typeof DashboardPostEditPostIdRoute
  LibraryIdPostIdRoute: typeof LibraryIdPostIdRoute
  DashboardPostContentIndexRoute: typeof DashboardPostContentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/create-organization': {
      id: '/owner/create-organization'
      path: '/owner/create-organization'
      fullPath: '/owner/create-organization'
      preLoaderRoute: typeof OwnerCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/create-admin': {
      id: '/owner/create-admin'
      path: '/owner/create-admin'
      fullPath: '/owner/create-admin'
      preLoaderRoute: typeof OwnerCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-new-password': {
      id: '/auth/set-new-password'
      path: '/auth/set-new-password'
      fullPath: '/auth/set-new-password'
      preLoaderRoute: typeof AuthSetNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/post-content/': {
      id: '/dashboard/post-content/'
      path: '/dashboard/post-content'
      fullPath: '/dashboard/post-content/'
      preLoaderRoute: typeof DashboardPostContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/id/$postId': {
      id: '/library/id/$postId'
      path: '/library/id/$postId'
      fullPath: '/library/id/$postId'
      preLoaderRoute: typeof LibraryIdPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/post-edit/$postId': {
      id: '/dashboard/post-edit/$postId'
      path: '/dashboard/post-edit/$postId'
      fullPath: '/dashboard/post-edit/$postId'
      preLoaderRoute: typeof DashboardPostEditPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSetNewPasswordRoute: AuthSetNewPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  OwnerCreateAdminRoute: OwnerCreateAdminRoute,
  OwnerCreateOrganizationRoute: OwnerCreateOrganizationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardPostEditPostIdRoute: DashboardPostEditPostIdRoute,
  LibraryIdPostIdRoute: LibraryIdPostIdRoute,
  DashboardPostContentIndexRoute: DashboardPostContentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
